# Generated by Django 4.2 on 2023-06-08 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulc_app', '0002_alter_dulcinea_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dulcinea',
            name='GM_rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dulcinea',
            name='RS_rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
