# Generated by Django 4.2 on 2023-06-08 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dulc_app', '0004_alter_dulcinea_gm_rate_alter_dulcinea_rs_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dulcinea',
            name='GM_rate',
            field=models.IntegerField(default='10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dulcinea',
            name='RS_rate',
            field=models.IntegerField(default='10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='dulcinea',
            name='date_1',
            field=models.DateField(),
        ),
    ]
