# Generated by Django 4.2 on 2023-06-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dulc_app', '0005_alter_dulcinea_gm_rate_alter_dulcinea_rs_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dulcinea',
            options={'ordering': ['date_1']},
        ),
    ]
